### ISSUE TITLE
dp_check compilation error

### ISSUE THREAD

**Issue by igorbernstein2** [GoogleCloudPlatform/grpc-gcp-tools#7]
```
./dp_check.go:112:13: initResp.LoadBalancerDelegate undefined (type *grpc_lb_v1.InitialLoadBalanceResponse has no field or method LoadBalancerDelegate)
```

**Comment by apolcyn** [comment]
The current code hasn't referenced the deleted `LoadBalancerDelegate` in some time, so I think this issue has been fixed.

@igorbernstein2 please do note that this tool is intended to be consumed mainly via the release page by fetching the plain executable, and we haven't really been paying attention to make sure that this tool always builds cleanly from source at latest github commit. However, if there's still an issue fetching the tool from the releases page, please let me know and I can try to find a more suitable approach.
